blueprint:
  source_url: https://github.com/niro1987/homeassistant-config/blob/master/blueprints/automation/niro1987/zha_ikea_tradfri_5button_remote_custom.yaml
  name: ZHA - IKEA TRADFRI - 5 Button Remote - Custom Actions
  description: This automation simulates the use of the IKEA TRADFRI remote control
    connected through ZHA.
  domain: automation
  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI remote control
    power_short:
      name: Short Press - Power Button
      description: The action to perform on Short Press of the Power Button
      selector:
        action: {}
      default: []
    dimup_short:
      name: Short Press - Dim Up Button
      description: The action to perform on Short Press of the Dim Up Button
      selector:
        action: {}
      default: []
    dimdown_short:
      name: Short Press - Dim Down Button
      description: The action to perform on Short Press of the Dim Down Button
      selector:
        action: {}
      default: []
    colorup_short:
      name: Short Press - Color Up Button
      description: The action to perform on Short Press of the Color Up Button
      selector:
        action: {}
      default: []
    colordown_short:
      name: Short Press - Color Down Button
      description: The action to perform on Short Press of the Color Down Button
      selector:
        action: {}
      default: []
    power_long:
      name: Long Press - Power Button
      description: The action to perform on Long Press of the Power Button
      selector:
        action: {}
      default: []
    dimup_long:
      name: Long Press - Dim Up Button
      description: The action to perform on Long Press of the Dim Up Button
      selector:
        action: {}
      default: []
    dimdown_long:
      name: Long Press - Dim Down Button
      description: The action to perform on Long Press of the Dim Down Button
      selector:
        action: {}
      default: []
    colorup_long:
      name: Long Press - Color Up Button
      description: The action to perform on Long Press of the Color Up Button
      selector:
        action: {}
      default: []
    colordown_long:
      name: Long Press - Color Down Button
      description: The action to perform on Long Press of the Color Down Button
      selector:
        action: {}
      default: []
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'remote'
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "toggle" }}'
    sequence: !input 'power_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "move_to_level_with_on_off"
        }}'
    sequence: !input 'power_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "step_with_on_off" }}'
    sequence: !input 'dimup_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
    sequence: !input 'dimup_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "step" }}'
    sequence: !input 'dimdown_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "move" }}'
    sequence: !input 'dimdown_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "press" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [256,13,0] }}'
    sequence: !input 'colorup_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "hold" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [3328,0] }}'
    sequence: !input 'colorup_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "press" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [257,13,0] }}'
    sequence: !input 'colordown_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "hold" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [3329,0] }}'
    sequence: !input 'colordown_long'
  default: []
