esphome:
  name: wave-switch

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e0d8c9ebea730b360756f89c883b59b0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wave-Switch Fallback Hotspot"
    password: "Z31tD0WKTCxO"

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO26
    echo_pin: GPIO25
    name: "Wave switch"
    update_interval: 0.3s